### PR TITLE
General improvements (2)

### LINKED ISSUE #5: missing natives and callbacks
There are few natives and callbacks which are missing in the includes of SAMP server package. Here are few (if not all) of the missing natives and callbacks:

**Missing Natives:**
- IsValidVehicle(vehicleid)
- SendClientCheck
- gpci

**Missing Callbacks:**
- OnClientCheckResponse
- OnScriptCash

I am not sure if it is safe to include some of these natives and callbacks. They could have been intentionally omitted from the includes so that people don't get to see them. They could be deprecated in a future version or even completely removed as it was not a part of the official SAMP includes set. Moreover, there's a lot of rumors about some of those natives and callbacks.

### LINKED ISSUE #11: a_http
Add a_http to a_samp, because for some mysterious reason it's missing by default.
```Pawn
#include <a_http>
```

### LINKED ISSUE #17: #pragma library samp
Isn't needed. Nor the others

### PR DESCRIPTION
**Pull request by Y-Less**
Reopening my last pull request.  Now has:

* Far more consistency in defines.  They are grouped together, evenly spaced, and limits can be overridden.
* Fixes #17 
* Fixes #11 
* Fixes #5 
* Informational constants.  `public const SAMP_INCLUDES_VERSION` for server checks.  `SAMP_CONST_CORRECT` for code checks.
* Updated limits in a_npc.

### CODE REVIEW

**Comment by ADRFranklin** [comment]
I like this a lot, I like the defined checks as well.

Good Stuff 👍

**Review by ADRFranklin — APPROVED** [review]
Approved!

**Review by Southclaws — APPROVED** [review]

**Comment by Southclaws** [comment]
Your versioning strategy actually solves the original blocker. 0.3.DL natives can be added to master and placed behind a version check.

**Comment by Southclaws** [comment]
But for now, it might be beneficial to provide a 0.3.DL specific include file with the new natives.

**Comment by Southclaws** [comment]
Because the 0.3.DL branch has missed out on important things like const correctness and all the other improvements.

**Comment by Y-Less** [comment]
Could make make a macro version and a public var version, then you can test the former in the includes and the latter in the server.

**Comment by Y-Less** [comment]
```pawn
#define SAMP_INCLUDES_VERSION_ 0x010223
public const SAMP_INCLUDES_VERSION = SAMP_INCLUDES_VERSION_;
#define SAMP_INCLUDES_VERSION SAMP_INCLUDES_VERSION_
```

**Pull request merged**
